version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - printenv
      - aws sts get-caller-identity
      - aws sts assume-role --role-arn arn:aws:iam::134071937287:role/service-role/codebuild-refinery-docs-build-service-role --role-session-name $(uuidgen)
      - exit -1
      - apt-get update
      - apt-get install -y s3cmd
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - mkdocs build
  post_build:
    commands:
      - s3cmd sync --acl-public --delete-removed ./site/ s3://testrefinerydocs/
artifacts:
    base-directory: .
    files: "**/*"