version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - mkdocs build
  post_build:
    commands:
      - aws s3 sync ./site/ s3://docs.refinery.io --acl public-read --cache-control public,max-age=600
artifacts:
    base-directory: .
    files: "**/*"