version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - pip install -r requirements.txt
      - mkdocs build
  post_build:
    commands:
      - s3cmd sync --acl-public --delete-removed ./site/ s3://testrefinerydocs/
artifacts:
    base-directory: .
    files: "**/*"